#!/usr/bin/env python3
"""Rebuild the repository indexes from manifest.json and every asset's state.json.

Writes START_HERE.html (offline gallery of produced assets), asset_index.csv, review/REMAINING_TICKETS.md and
review/summary.json. Never writes inside an asset folder; gallery thumbnails go to review/gallery/.

  python tools/build_indexes.py
"""
from __future__ import annotations

import csv
import io
import json
from collections import Counter
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/devin-thomas/vb-video"
FAMILIES = {"cards": "Opening / end cards", "chapters": "Chapter cards", "code": "Code cards",
            "comparisons": "C# / VB comparisons", "diagrams": "Diagrams", "facts": "Fact cards", "mockups": "Mockups",
            "reference-code": "Reference code", "captures": "Terminal and editor captures", "stills": "Stills",
            "historical": "Historical images", "broll": "B-roll", "ops": "Coordination"}


def load(path: Path):
    return json.loads(path.read_bytes().decode("utf-8"))


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))


def family(row: dict) -> str:
    return row["asset_dir"].split("/")[1]


def issue_link(number: int | None, prefix: str = "") -> str:
    return f"[#{number}]({REPO_URL}/issues/{number})" if number else ""


def asset_index(rows: list[dict], states: dict[str, dict]) -> None:
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(["id", "title", "family", "kind", "lane", "original_family", "script_sections", "dependencies",
                     "release_gates", "asset_dir", "ticket", "github_issue", "production_status", "release_status"])
    for r in rows:
        s = states[r["id"]]
        writer.writerow([r["id"], r["title"], family(r), r["kind"], r["lane"], r["parent"],
                         ",".join(map(str, r["sections"])), ",".join(r["deps"]), ",".join(r["gates"]), r["asset_dir"],
                         r["ticket"], r.get("github_issue", ""), s["production_status"], s["release_status"]])
    write(ROOT / "asset_index.csv", out.getvalue())


def remaining(rows: list[dict], states: dict[str, dict], manifest: dict) -> None:
    lines = ["# Remaining tickets", "",
             "Generated by `python tools/build_indexes.py` from each asset's `state.json`. GitHub issues are the tracker: "
             f"[open issues]({REPO_URL}/issues).", ""]

    def entry(r: dict, extra: str = "") -> str:
        issue = issue_link(r.get("github_issue"))
        return (f"- [{r['id']} — {r['title']}](../{r['ticket']})" + (f" · {issue}" if issue else "")
                + (f" · {extra}" if extra else ""))

    in_progress = [r for r in rows if states[r["id"]]["production_status"] == "in_progress"]
    if in_progress:
        lines += ["## In progress", ""] + [entry(r) for r in in_progress] + [""]
    planned = [r for r in rows if states[r["id"]]["production_status"] in ("planned", "blocked")]
    lines += ["## Not started", ""]
    for kind in ["support", "archive", "scout", "still", "capture", "motion", "code"]:
        group = [r for r in planned if r["kind"] == kind]
        if group:
            lines += [f"### {kind.title()}", ""] + [entry(r, "waiting on " + ", ".join(
                d for d in r["deps"] if states[d]["production_status"] not in ("produced", "reviewed"))
                if any(states[d]["production_status"] not in ("produced", "reviewed") for d in r["deps"]) else "")
                for r in group] + [""]
    review = [r for r in rows if states[r["id"]]["production_status"] == "produced" and states[r["id"]]["release_status"] != "approved"]
    lines += ["## Produced, release not yet approved", "",
              f"{len(review)} produced assets still need a producer release decision. Open editorial gates are listed; "
              "an asset with no gates only needs the producer's approval.", ""]
    lines += [entry(r, ("gates " + ", ".join(r["gates"])) if r["gates"] else "no gates") for r in review] + [""]
    lines += ["## Human / capability handoffs", ""]
    for path in sorted((ROOT / "docs/handoffs").glob("H*.md")):
        title = path.read_bytes().decode("utf-8").splitlines()[0].lstrip("# ").strip()
        issue = issue_link(manifest.get("handoff_issues", {}).get(path.stem))
        lines.append(f"- [{title}](../docs/handoffs/{path.name})" + (f" · {issue}" if issue else ""))
    write(ROOT / "review/REMAINING_TICKETS.md", "\n".join(lines) + "\n")


def gallery_items(rows: list[dict], states: dict[str, dict]) -> list[dict]:
    items = []
    thumbs = ROOT / "review/gallery"
    thumbs.mkdir(parents=True, exist_ok=True)
    for r in rows:
        s = states[r["id"]]
        if s["production_status"] != "produced" or r["kind"] == "support":
            continue
        base = ROOT / r["asset_dir"]
        poster = next((base / p for p in ["exports/poster.png", "exports/framed.png"] if (base / p).exists()), None)
        if poster is None:
            print(f"warning: {r['id']} has no poster PNG; left out of the gallery")
            continue
        rel = lambda p: p.relative_to(ROOT).as_posix()
        thumb = thumbs / f"{r['id']}.jpg"
        image = Image.open(poster).convert("RGB")
        image.thumbnail((640, 360), Image.Resampling.LANCZOS)
        canvas = Image.new("RGB", (640, 360), "#08090c")
        canvas.paste(image, ((640 - image.width) // 2, (360 - image.height) // 2))
        canvas.save(thumb, quality=86, optimize=True)
        delivery = load(base / "delivery.json") if (base / "delivery.json").exists() else {}
        variants = []
        for png in sorted((base / "exports").glob("*.png")):
            if png.name == "contact-sheet.png":
                continue
            mp4, svg = base / "exports" / f"{png.stem}.mp4", base / "src" / f"variant-{png.stem}.svg"
            variants.append({"name": png.stem, "png": rel(png), "mp4": rel(mp4) if mp4.exists() else None,
                             "svg": rel(svg) if svg.exists() else None})
        video = base / "exports/preview.mp4"
        source = base / "src/index.html"
        items.append({
            "id": r["id"], "title": r["title"], "group": family(r), "poster": rel(poster), "thumb": rel(thumb),
            "video": rel(video) if video.exists() else None, "source": rel(source) if source.exists() else None,
            "ticket": r["ticket"], "issue": f"{REPO_URL}/issues/{r['github_issue']}" if r.get("github_issue") else None,
            "qa": rel(base / "qa.md") if (base / "qa.md").exists() else None,
            "duration_seconds": delivery.get("duration_seconds"), "gates": delivery.get("unresolved_gates", r["gates"]),
            "release": s["release_status"], "variants": variants})
    return items


PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual Basic War — Asset gallery</title><style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#111318;color:#f1f3f5}*{box-sizing:border-box}body{margin:0}header{padding:28px 32px 22px;border-bottom:1px solid #303840}h1{font-size:25px;font-weight:650;margin:0 0 12px}header p{color:#aeb6bf;margin:10px 0;font-size:14px}a{color:#91bcff;text-underline-offset:3px}nav{display:flex;gap:18px;flex-wrap:wrap}main{padding:22px 32px 50px;max-width:1900px;margin:auto}.filters{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:22px}input,select,button{font:inherit;border:1px solid #46515d;border-radius:3px;background:#1b2027;color:inherit;padding:11px 13px}input{min-width:240px;flex:1;max-width:470px}button{cursor:pointer}#count{color:#aeb6bf;font-size:14px;margin-left:auto}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:25px 20px}.tile{border:0;background:none;padding:0;text-align:left;display:block;width:100%;color:inherit}.tile img{width:100%;aspect-ratio:16/9;object-fit:contain;display:block;border:1px solid #323b46;background:#08090c}.tile h2{font-size:15px;font-weight:600;line-height:1.4;margin:10px 0 4px}.meta{font-size:12px;color:#aeb6bf}dialog{width:min(1500px,96vw);max-height:95vh;border:1px solid #485460;background:#111318;color:inherit;padding:20px;border-radius:4px}dialog::backdrop{background:#000c}.dialogtop{display:flex;align-items:center;gap:12px;margin-bottom:14px}.dialogtop h2{font-size:18px;margin:0;flex:1}.media{background:#000}.media video,.media img{display:block;width:100%;max-height:65vh;object-fit:contain}.tools{display:flex;gap:17px;flex-wrap:wrap;align-items:center;margin-top:17px}.note{color:#c4cbd2;font-size:14px;line-height:1.6}@media(max-width:600px){header,main{padding:20px 16px}.grid{grid-template-columns:1fr}dialog{padding:12px}#count{margin-left:0;width:100%}}
</style></head><body><header><h1>Visual Basic War · Asset gallery</h1><nav><a href="README.md">Repository guide</a><a href="review/REMAINING_TICKETS.md">Remaining tickets</a><a href="__ISSUES__">GitHub issues</a><a href="review/PREVIEW_REEL.mp4">Preview reel (session 1)</a><a href="assets/ops/OPS-01/exports/card-atlas.png">Card atlas</a></nav><p>__COUNT__ produced assets · 1920 × 1080 · motion at 30 fps · silent. Generated by tools/build_indexes.py.</p></header><main><div class="filters"><input id="search" type="search" placeholder="Find a ticket or asset" aria-label="Find a ticket or asset"><select id="group" aria-label="Asset family"><option value="">All families</option>__OPTIONS__</select><span id="count"></span></div><div class="grid" id="grid"></div></main><dialog id="dialog"><div class="dialogtop"><h2 id="title"></h2><button id="close" aria-label="Close preview">Close</button></div><div class="media" id="media"></div><div class="tools"><select id="variant" aria-label="Variant"></select><a id="png" href="#">PNG</a><a id="mp4" href="#">MP4</a><a id="svg" href="#">SVG</a><a id="source" href="#">HTML source</a><a id="ticket" href="#">Ticket</a><a id="issue" href="#">Issue</a><a id="qa" href="#">QA</a></div><p class="note" id="note"></p></dialog><script>
const assets=__DATA__,grid=document.getElementById('grid'),search=document.getElementById('search'),group=document.getElementById('group'),dlg=document.getElementById('dialog');let current=null;
function link(id,href){const el=document.getElementById(id);el.hidden=!href;if(href)el.href=href}
function render(){const q=search.value.toLowerCase(),items=assets.filter(a=>(!group.value||a.group===group.value)&&(!q||(a.id+' '+a.title).toLowerCase().includes(q)));document.getElementById('count').textContent=items.length+' assets';grid.replaceChildren();for(const a of items){const b=document.createElement('button');b.className='tile';const img=document.createElement('img');img.src=a.thumb;img.alt=a.title;img.loading='lazy';b.append(img);const h=document.createElement('h2');h.textContent=a.title;b.append(h);const m=document.createElement('div');m.className='meta';m.textContent=a.id+' · '+(a.duration_seconds?a.duration_seconds+' s':'Still')+' · release '+a.release;b.append(m);b.onclick=()=>open(a);grid.append(b)}}
function setmedia(png,mp4,svg){const media=document.getElementById('media');media.replaceChildren();let el;if(mp4){el=document.createElement('video');el.src=mp4;el.controls=true;el.playsInline=true;el.preload='metadata';el.poster=png}else{el=document.createElement('img');el.src=png;el.alt=current.title}media.append(el);link('png',png);link('mp4',mp4);link('svg',svg)}
function open(a){current=a;document.getElementById('title').textContent=a.id+' · '+a.title;link('source',a.source);link('ticket',a.ticket);link('issue',a.issue);link('qa',a.qa);const v=document.getElementById('variant');v.replaceChildren();v.add(new Option('Main preview','-1'));a.variants.forEach((x,i)=>v.add(new Option(x.name,i)));v.onchange=()=>{const i=Number(v.value);if(i<0)setmedia(a.poster,a.video,null);else{const x=a.variants[i];setmedia(x.png,x.mp4,x.svg)}};v.onchange();document.getElementById('note').textContent=a.release==='approved'?'Produced and release-approved by the producer.':a.gates.length?'Produced. Editorial gates still open: '+a.gates.join(', ')+'. Review QA before publication.':'Produced. Release not yet reviewed by the producer.';dlg.showModal()}
document.getElementById('close').onclick=()=>dlg.close();dlg.addEventListener('close',()=>document.getElementById('media').replaceChildren());search.oninput=render;group.onchange=render;render();
</script></body></html>
"""


def gallery(items: list[dict]) -> None:
    present = {i["group"] for i in items}
    options = "".join(f'<option value="{k}">{v}</option>' for k, v in FAMILIES.items() if k in present)
    data = json.dumps(items, ensure_ascii=False).replace("</", "<\\/")
    page = (PAGE.replace("__DATA__", data).replace("__OPTIONS__", options).replace("__COUNT__", str(len(items)))
            .replace("__ISSUES__", f"{REPO_URL}/issues"))
    write(ROOT / "START_HERE.html", page)


def summary(rows: list[dict], states: dict[str, dict], items: list[dict]) -> None:
    data = {
        "tickets": len(rows),
        "production_status": dict(Counter(s["production_status"] for s in states.values())),
        "release_status": dict(Counter(s["release_status"] for s in states.values())),
        "produced_by_family": dict(Counter(family(r) for r in rows if states[r["id"]]["production_status"] == "produced")),
        "gallery_assets": len(items),
        "mp4_files": len(list((ROOT / "assets").glob("*/*/exports/*.mp4"))),
        "issues_recorded": sum(bool(r.get("github_issue")) for r in rows),
    }
    write(ROOT / "review/summary.json", json.dumps(data, indent=2) + "\n")
    print(json.dumps(data, indent=2))


def main() -> int:
    manifest = load(ROOT / "manifest.json")
    rows = manifest["tickets"]
    states = {r["id"]: load(ROOT / r["asset_dir"] / "state.json") for r in rows}
    asset_index(rows, states)
    remaining(rows, states, manifest)
    items = gallery_items(rows, states)
    gallery(items)
    summary(rows, states, items)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
